### ISSUE TITLE
Build  FROST-Server.Plugin.STAplus-2.2.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by paulau** [securedimensions/FROST-Server-PLUS#10]
Dear developers,

I try to use your Repository to incorporate into frost Server. 
by compilation with "maven compile" (with java 17), I got error: 

[ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for de.securedimensions.FROST-Server:FROST-Server.Plugin.STAplus:2.2.0-SNAPSHOT: The following artifacts could not be resolved: de.fraunhofer.iosb.ilt.FROST-Server:FROST-Server.Plugins:pom:2.2.0-SNAPSHOT (absent): de.fraunhofer.iosb.ilt.FROST-Server:FROST-Server.Plugins:pom:2.2.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt.

Apparently, because I do not have access to https://oss.sonatype.org/content/repositories/snapshots/  
Would it be possible to update pom.xml of your project with the use of publicly avalable repository?

Or: would it be possible to find other solution of this problem? 

Greetings, 
Pavel

**Comment by securedimensions** [comment]
Pavel,

STAplus plugin now builds with FROST-Server v2.2.x

Best
Andreas
