### ISSUE TITLE
Party: authId and @iot.id have different values

### ISSUE THREAD

**Issue by Cedric-Crettaz** [securedimensions/FROST-Server-PLUS#12]
When creating a Party with a correct authId or an empty authId, the FROST/STA server returns a successful creation of the new Party, but authId and @iot.id are different. Based on the source code of the STAplus plugin, it is supposed that both should have the same value.

**Comment by securedimensions** [comment]
Are you using an Authentication Plugin?

Is `plugins.staplus.enable.enforceOwnership` enabled?

**Comment by Cedric-Crettaz** [comment]
Yes, we are using your authentication plugin.
Yes, enforceOwnership = true

**Comment by securedimensions** [comment]
Please post the FROST-Server.logSent from the roadAm 02.05.2024 um 18:06 schrieb Cédric Crettaz ***@***.***>:﻿
Yes, we are using your authentication plugin.
Yes, enforceOwnership = true

**Comment by Cedric-Crettaz** [comment]
There is this warning:
06:55:09.753 [http-nio-8080-exec-4] WARN  d.f.i.i.f.p.p.PostgresPersistenceManager - idGenerationMode is 'SERVER_GENERATED_ONLY' but @iot.id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is present. Ignoring @iot.id.

**Comment by Cedric-Crettaz** [comment]
Finally, I found the error: I stupidly forgot to set  `persistence.idGenerationMode.Party=ClientGeneratedOnly`. And yet, I have read the documentation at [Party Singleton/Setting](https://github.com/securedimensions/FROST-Server-PLUS?tab=readme-ov-file#setting) :-(
