### ISSUE TITLE
Deployment of STAplus plugin on an existing FROST-Server 2.3.2

### ISSUE THREAD

**Issue by eskotilla** [securedimensions/FROST-Server-PLUS#13]
Hi, we have deployed a FROST-Server and we were trying to enable STAPlus plugin.

We've read that this repository builds with the FROST-Server v2.2.0, and we want to know if it's possible to enable it within a 2.3.2 FROST-Server's version.

We have done "mvn install", and placed "FROST-Server.Plugin.STAplus-2.2.0.jar" into WEB-INF/lib folder, and we've added the following lines in META-INF/context.xml file to get it to work:

\<Parameter override="false" name="plugins.plugins" value="de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginActuation,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginBatchProcessing,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginCoreModel,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginFormatCsv,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginFormatDataArray,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginFormatGeoJson,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginModelLoader,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginMultiDatastream,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginOData,
                                                              de.fraunhofer.iosb.ilt.sta.plugins.FROSTPluginOpenApi,
                                                              de.securedimensions.frostserver.plugin.staplus" />

\<Parameter override="false" name="plugins.staplus.enable" value="true" />
\<Parameter override="false" name="plugins.staplus.enable.enforceOwnership" value="false" />
\<Parameter override="false" name="plugins.staplus.enable.plugins.staplus.enable.enforceLicensing" value="false" />

We have restarted TOMCAT but it seems plugin is not enabled.

Could you please guide us to get it working?

Thanks

**Comment by securedimensions** [comment]
Release management is on it's way shortly. This will provide the plugin for FROST v2.3.2 and v2.4.

**Comment by securedimensions** [comment]
Building the STAplus plugin for most existing FROST-Server versions is now available via tags. Please choose the Release/Tag that matches your FROST-Server version.
