### ISSUE TITLE
Cannot create a Group

### ISSUE THREAD

**Issue by joanma747** [securedimensions/FROST-Server-PLUS#6]
I'm trying to POST this:
{
  "name": "https://www.inaturalist.org/observations/118684011",
  "description": "Observation of a Bach- Kratzdistel",
  "creationTime": "2022-05-25T19:15:09.856Z"
}

in here: 

https://cos4cloud.demo.secure-dimensions.de/staplus/v1.1/Groups

and I get:
{
    "code": 500,
    "type": "error",
    "message": "Failed to store data."
}

I'm not able to guess what happens and this has worked in the past.

Can you help me?

Thanks,

**Comment by hylkevds** [comment]
"Failed to store data" means there was a database exception. Details 
should be in the log file.

**Comment by joanma747** [comment]
Seems to work now.

**Comment by securedimensions** [comment]
The issue is that when creating a Group that already exist (identified by the 'name' attribute), the server should return 201 if the other information is identical. Otherwise the server should return more helpful information on the error - not just "500" status.
