### ISSUE TITLE
Datastream not linked to party error without enforceOwnership

### ISSUE THREAD

**Issue by nbrinckm** [securedimensions/FROST-Server-PLUS#7]
Dear developers,

I have some strange behaviour when trying to put/patch a datastream: Basically the frost server complains that the datastream is not associated with any party entry. It lets my create those datastreams in the first place - which is also the intended behaviour from my point of view with `plugins.staplus.enable.enforceOwnership=false`.

This is currently based on the frost image: [develop-2.x-2.2.0-SNAPSHOT](https://hub.docker.com/layers/fraunhoferiosb/frost-server/develop-2.x-2.2.0-SNAPSHOT/images/sha256-28537509a94ff200f9facf25dc181bfc3a111d532dc4e25545e1b6038eed6971?context=explore)

and the `[a5648ce](https://github.com/securedimensions/FROST-Server-PLUS/commit/a5648cec91b85ee47019743e3bbaa1e0dfa1d05f)` commit of this repo here.

Maybe some code to reproduce my behaviour here (in python) on an empty Frost Server with STA Plus extension:

```python

import requests

requests.post(
    "http://localhost:8080/FROST-Server/v1.1/Sensors",
    json={
        "name": "example sensor",
        "description": "desc",
        "encodingType": "https://opengis.net/doc/IS/SensorML/2.0",
        "metadata": "https://url.to/sensorML",
        "properties": {},
    },
)

requests.post(
    "http://localhost:8080/FROST-Server/v1.1/Things",
    json={"name": "example thing", "description": "desc", "properties": {}},
)

requests.post(
    "http://localhost:8080/FROST-Server/v1.1/ObservedProperties",
    json={
        "name": "example property",
        "definition": "def",
        "description": "desc",
        "properties": {},
    },
)

# That still works
requests.post(
    "http://localhost:8080/FROST-Server/v1.1/Datastreams",
    json={
        "name": "example datastream",
        "description": "desc",
        "observationType": "OM_Observation",
        "unitOfMeasurement": {"name": "n", "symbol": "n", "definition": "..."},
        "Thing": {"@iot.id": 1},
        "Sensor": {"@iot.id": 1},
        "ObservedProperty": {"@iot.id": 1},
        "properties": {},
    },
)

# That doesn't
response = requests.put(
    "http://localhost:8080/FROST-Server/v1.1/Datastreams(1)",
    json={
        "name": "new name",
        "description": "desc",
        "observationType": "OM_Observation",
        "unitOfMeasurement": {"name": "n", "symbol": "n", "definition": "..."},
        "Thing": {"@iot.id": 1},
        "Sensor": {"@iot.id": 1},
        "ObservedProperty": {"@iot.id": 1},
        "properties": {},
    },
)

print(response.text)
```

Error:

```
{"code":400,"type":"error","message":"Datastream not linked to a Party"}
```

I checked the value it takes for `plugins.staplus.enable.enforceOwnership` in the logs of the frost server. In default case it should be disabled - but even setting it explicitly to `false` still gives my this kind of error.

I would just expect that it should still allow me to update datastreams without having adding a related party in this case.

**Comment by nbrinckm** [comment]
By the way: In the readme there is `plugins.plus.enable.enforceOwnership` while the logs in the frost server uses `plugins.staplus.enable.enforceOwnership`.

I just used `plugins.staplus.enable.enforceOwnership` as most of the entries in the readme here use the `plugins.staplus` prefix - and as I saw it in the logs this way.

**Comment by securedimensions** [comment]
Thank you for spotting these! Both issues are now fixed.
