### ISSUE TITLE
Docker configuration issues

### ISSUE THREAD

**Issue by webb-ben** [securedimensions/FROST-Server-PLUS#8]
@hylkevds as a part of WQX I am attempting to get a version of FROST up and running with the expanded STA Plus Entities. I am struggling to build a Docker image with the STA Plus plugin enabled. The provided documentation is enough to get me a Dockerfile, but I am struggling to build a Dockerfile that does not produce errors. I am working with:

```
FROM maven:3.8.4-openjdk-17 AS builder

WORKDIR /app
COPY . /app
RUN mvn -B -DskipTests -Dmaven.javadoc.skip=true install

FROM fraunhoferiosb/frost-server-http:develop-2.x-2.2.0-SNAPSHOT

# Copy the STAplus plugin JAR file to the appropriate directory
COPY /app/target/FROST-Server.Plugin.STAplus-2.2.0-SNAPSHOT.jar ${CATALINA_HOME}/webapps/FROST-Server/WEB-INF/lib/

# Set environment variables for STAplus plugin
ENV plugins_staplus_enable=true
ENV plugins_staplus_enable_enforceOwnership=true
ENV plugins_staplus_enable_enforceLicensing=true
ENV plugins_staplus_enable_enforceObservationGroupLicensing=true

USER tomcat
```

The plugin, as written, almost looks like it should be inside of the FROST-Sever repository during the build but seeing as I am primarily a python developer, I have been struggling make progress.

Any advice or help would be greatly appreciated!

**Comment by hylkevds** [comment]
I was not familiar with Docker multi-stage builds, but looking at [the docs](https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds), it seems your COPY command is missing the  `--from=builder`.

You also need `-Dspotless.check.skip` in the maven install command, since it tries to use files that are not in this repo.

The build can be sped up a lot on subsequent builds by [caching the maven downloads](https://www.baeldung.com/ops/docker-cache-maven-dependencies):

```
FROM maven:3.8.4-openjdk-17 AS builder

WORKDIR /app
ADD pom.xml $HOME
RUN mvn verify --fail-never

COPY . /app
RUN mvn -B -DskipTests -Dmaven.javadoc.skip=true -Dspotless.check.skip install
```

And finally, you'll need to tell FROST to load the PLUS plugin using:
```
ENV plugins_plugins=de.securedimensions.frostserver.plugin.staplus.PluginPLUS
```

So that should result in:
```
FROM maven:3.8.4-openjdk-17 AS builder

WORKDIR /app
ADD pom.xml $HOME
RUN mvn verify --fail-never

COPY . /app
RUN mvn -B -DskipTests -Dmaven.javadoc.skip=true -Dspotless.check.skip install

FROM fraunhoferiosb/frost-server-http:2.2.0-SNAPSHOT

# Copy the STAplus plugin JAR file to the appropriate directory
COPY --from=builder /app/target/FROST-Server.Plugin.STAplus-2.2.0-SNAPSHOT.jar ${CATALINA_HOME}/webapps/FROST-Server/WEB-INF/lib/

# Set environment variables for STAplus plugin
ENV plugins_plugins=de.securedimensions.frostserver.plugin.staplus.PluginPLUS
ENV plugins_staplus_enable=true
ENV plugins_staplus_enable_enforceOwnership=true
ENV plugins_staplus_enable_enforceLicensing=true
ENV plugins_staplus_enable_enforceObservationGroupLicensing=true

USER tomcat
```

**Comment by webb-ben** [comment]
Yes it seems like I somehow managed to delete the `--from=builder` right before I copied the contents of my working Dockerfile over. 

The Dockerfile you provided at the end works! Thank you. 

I published the image to [internetofwater/frost-server-http-plus](https://hub.docker.com/r/internetofwater/frost-server-http-plus).
